CREATE TABLE USERS(
USERID Int PRIMARY KEY,
EMAIL Varchar(30) NOT NULL UNIQUE,
NAME Varchar(50) NOT NULL,
PSWD Varchar(30) NOT NULL
);

CREATE TABLE FRIENDS(
USERID INT NOT NULL,
FID INT NOT NULL,
PRIMARY KEY(FID, USERID),
FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
FOREIGN KEY (FID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

CREATE TABLE PLACE(
NAME Varchar(30) NOT NULL,
PLACEID Int PRIMARY KEY,
TYPE Varchar(10) CHECK (TYPE in ('country', 'city', 'state', 'other'))
);

CREATE TABLE PHOTO(
FILENAME Varchar(30) NOT NULL,
PHOTOID Int PRIMARY KEY,
PLACEID Int,
AUTHOR Int NOT NULL,
DATE_TAKEN DATE,
FOREIGN KEY(AUTHOR) REFERENCES USERS(USERID) ON DELETE CASCADE,
FOREIGN KEY(PLACEID) REFERENCES PLACE(PLACEID) ON DELETE CASCADE
);

CREATE TABLE REACTION(
REACTIONID Int PRIMARY KEY,
TYPE Varchar(10) CHECK (TYPE in ('like', 'love', 'laugh', 'dislike', 'angry')),
AUTHOR Int,
PHOTOID Int,
FOREIGN KEY (AUTHOR) REFERENCES USERS(USERID) ON DELETE CASCADE,
FOREIGN KEY (PHOTOID) REFERENCES PHOTO(PHOTOID) ON DELETE CASCADE,
CONSTRAINT unique_author unique("AUTHOR","PHOTOID")
);

CREATE TABLE COMMENTS(
COMMENTID Int PRIMARY KEY,
TEXT Varchar(100) NOT NULL,
AUTHOR Int NOT NULL,
PHOTOID Int NOT NULL,
FOREIGN KEY (AUTHOR) REFERENCES USERS(USERID) ON DELETE CASCADE,
FOREIGN KEY (PHOTOID) REFERENCES PHOTO(PHOTOID) ON DELETE CASCADE
);

CREATE TABLE REVIEW(
REVIEWID Int PRIMARY KEY,
TEXT Varchar(500) NOT NULL,
AUTHOR Int NOT NULL,
PLACEID Int NOT NULL,
FOREIGN KEY (AUTHOR) REFERENCES USERS(USERID) ON DELETE CASCADE,
FOREIGN KEY (PLACEID) REFERENCES PLACE(PLACEID) ON DELETE CASCADE
);

CREATE TABLE ADDRESS(
USERID Int NOT NULL,
STREET varchar(100) NOT NULL,
CITY varchar(55) NOT NULL,
STATE varchar(20) NOT NULL,
COUNTRY VARCHAR(20 ) NOT NULL,
ZIP Int,
FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

CREATE TABLE TRANSPO_INFO(
PLACEID Int NOT NULL,
TYPE Varchar(30) NOT NULL,
FOREIGN KEY (PLACEID) REFERENCES PLACE(PLACEID) ON DELETE CASCADE
);

CREATE TABLE WISHLIST(
USERID Int NOT NULL,
PLACEID Int NOT NULL,
PRIMARY KEY(USERID, PLACEID),
FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
FOREIGN KEY(PLACEID) REFERENCES PLACE(PLACEID) ON DELETE CASCADE
);

CREATE TABLE VISIT(
USERID Int NOT NULL,
PLACEID Int NOT NULL,
STARTDATE DATE NOT NULL,
ENDDATE DATE NOT NULL,
--PRIMARY KEY(USERID, PLACEID),
FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
FOREIGN KEY(PLACEID) REFERENCES PLACE(PLACEID) ON DELETE CASCADE
);
