DROP TABLE FRIENDS CASCADE CONSTRAINTS ;

DROP TABLE USERS CASCADE CONSTRAINTS ;

DROP TABLE PLACE CASCADE CONSTRAINTS ;

DROP TABLE PHOTO CASCADE CONSTRAINTS ;

DROP TABLE REACTION CASCADE CONSTRAINTS ;

DROP TABLE COMMENTS CASCADE CONSTRAINTS ;

DROP TABLE REVIEW CASCADE CONSTRAINTS ;

DROP TABLE ADDRESS CASCADE CONSTRAINTS ;

DROP TABLE TRANSPO_INFO CASCADE CONSTRAINTS ;

DROP TABLE WISHLIST CASCADE CONSTRAINTS ;

DROP TABLE VISIT CASCADE CONSTRAINTS ;